import {SDDebug, SDPlugin, SDPropertyInspector, SDInit, SDOnEvent, SDReady} from "./decorators/decorator-declarations";
import { AcdData,
	Coordinates,
	TitleParameters,
	PossibleEventsToReceive,
	PossibleEventsForAllToReceive,
	PossibleEventsForPiToReceive,
	PossibleEventsForActionToReceive,
	PossibleEventsToSend,
	PossibleEventsForAllToSend,
	PossibleEventsForPiToSend,
	PossibleEventsForActionToSend,
	InitEvent,
	InitEventInfo,
	InitEventInfoApplication,
	InitEventInfoPlugin,
	InitEventInfoDevice,
	InitEventInfoDeviceSize,
	InitEventActionInfo,
	InitEventActionInfoPayload,
	SystemDidWakeUpEvent,
	DidReceiveGlobalSettingsEvent,
	DidReceiveSettingsEvent,
	SendToPiEvent,
	SendToPluginEvent,
	PropertyInspectorDidAppearEvent,
	PropertyInspectorDidDisappearEvent,
	TitleParametersDidChangeEvent,
	KeyDownEvent,
	KeyUpEvent,
	DeviceDidConnectEvent,
	DeviceDidDisconnectEvent,
	ApplicationDidLaunchEvent,
	ApplicationDidTerminateEvent,
	WillAppearEvent,
	WillDisappearEvent } from "./interfaces/interface-declarations";
import {StreamDeckPlugin} from "./stream-deck-plugin";

export {StreamDeckPlugin}
export {SDDebug, SDPlugin, SDPropertyInspector, SDInit, SDOnEvent, SDReady}
export {
	AcdData,
	Coordinates,
	TitleParameters,
	PossibleEventsToReceive,
	PossibleEventsForAllToReceive,
	PossibleEventsForPiToReceive,
	PossibleEventsForActionToReceive,
	PossibleEventsToSend,
	PossibleEventsForAllToSend,
	PossibleEventsForPiToSend,
	PossibleEventsForActionToSend,
	InitEvent,
	InitEventInfo,
	InitEventInfoApplication,
	InitEventInfoPlugin,
	InitEventInfoDevice,
	InitEventInfoDeviceSize,
	InitEventActionInfo,
	InitEventActionInfoPayload,
	SystemDidWakeUpEvent,
	DidReceiveGlobalSettingsEvent,
	DidReceiveSettingsEvent,
	SendToPiEvent,
	SendToPluginEvent,
	PropertyInspectorDidAppearEvent,
	PropertyInspectorDidDisappearEvent,
	TitleParametersDidChangeEvent,
	KeyDownEvent,
	KeyUpEvent,
	DeviceDidConnectEvent,
	DeviceDidDisconnectEvent,
	ApplicationDidLaunchEvent,
	ApplicationDidTerminateEvent,
	WillAppearEvent,
	WillDisappearEvent
}

