name: Build
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to NPM
    needs: [sonarcloud]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
